# CUDA

In [39]:
if torch.cuda.is_available():
    device = torch.device("cuda")

In [40]:
device

device(type='cuda')

# Tensor Basics

## Creation

In [1]:
import torch

In [7]:
x = torch.empty(2, 3)

In [8]:
x

tensor([[1.7395e-04, 1.0470e-11, 2.6368e-09],
        [3.2688e+21, 4.4150e-05, 1.6132e-07]])

In [9]:
y = torch.rand(2, 3)

In [10]:
y

tensor([[0.3713, 0.0219, 0.5562],
        [0.0772, 0.1334, 0.9601]])

In [12]:
y.dtype

torch.float32

In [16]:
z = torch.rand(2, 3, dtype=torch.double)

In [17]:
z.dtype

torch.float64

In [18]:
a = torch.tensor([2.4, 5.1])

In [19]:
a

tensor([2.4000, 5.1000])

## Operations

In [20]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [21]:
z = x+y

In [22]:
x[0], y[0], z[0]

(tensor([0.4203, 0.3777]), tensor([0.4548, 0.9451]), tensor([0.8751, 1.3228]))

In [23]:
z = torch.add(x,y)

In [24]:
x[0], y[0], z[0]

(tensor([0.4203, 0.3777]), tensor([0.4548, 0.9451]), tensor([0.8751, 1.3228]))

In [25]:
y.add(x)

tensor([[0.8751, 1.3228],
        [0.6577, 0.4828]])

In [27]:
y

tensor([[0.4548, 0.9451],
        [0.6514, 0.3673]])

In [28]:
y.add_(x)

tensor([[0.8751, 1.3228],
        [0.6577, 0.4828]])

In [29]:
y

tensor([[0.8751, 1.3228],
        [0.6577, 0.4828]])

In [30]:
x = torch.rand(5,3)

In [31]:
x

tensor([[0.0961, 0.5747, 0.1321],
        [0.7591, 0.1311, 0.7719],
        [0.9034, 0.3828, 0.2338],
        [0.4567, 0.9937, 0.7908],
        [0.2447, 0.6348, 0.5684]])

In [32]:
x[:, 0]

tensor([0.0961, 0.7591, 0.9034, 0.4567, 0.2447])

In [33]:
x[1, :]

tensor([0.7591, 0.1311, 0.7719])

In [34]:
x[0,0]

tensor(0.0961)

In [35]:
x[0,0].item()

0.09612655639648438

In [36]:
x.shape

torch.Size([5, 3])

In [38]:
x.view(-1, 5).shape

torch.Size([3, 5])

In [43]:
# do this if you need to optimize this tensor
x = torch.rand(5, requires_grad=True)

In [44]:
x

tensor([0.6359, 0.6476, 0.8797, 0.4327, 0.9087], requires_grad=True)

# Gradient Calculation with Autograd

In [47]:
x = torch.randn(3, requires_grad=True)

In [48]:
x

tensor([ 0.0141, -0.0536,  0.7641], requires_grad=True)

In [49]:
y = x+2

In [50]:
y

tensor([2.0141, 1.9464, 2.7641], grad_fn=<AddBackward0>)

In [53]:
z = y*y*2

In [54]:
z

tensor([ 8.1132,  7.5770, 15.2806], grad_fn=<MulBackward0>)

In [55]:
z = z.mean()

In [56]:
z

tensor(10.3236, grad_fn=<MeanBackward0>)

In [57]:
z.backward()

In [58]:
x.grad

tensor([2.6855, 2.5952, 3.6855])

## Dummy Training

In [65]:
weights= torch.ones(4, requires_grad=True)

In [66]:
for epoch in range(3):
    output = (weights*3).sum()
    
    output.backward()
    
    print(weights.grad)
    
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
